Adds (post): gentle introduction to distributed authorization in CanDIG
CanDIG/candig.github.io pull request #20
Opened 2020-03-05 04:10 UTC by amanjeev

@ljdursi This is a very simple introduction. Please review.

2020-03-19 19:42 UTC, ljdursi requested changes
I think this is a very nice introduction.  Please take a look at the couple small tweaks I've proposed at the beginning, but otherwise this is great.

2020-03-19 19:42 UTC, ljdursi commented on _posts/2020-03-04-gentle-intro-to-federated-distributed-authz.md
> +its privacy regulations. This is where CanDIG, as a platform, helps. It is a
I'd say more of the health research environment than the healthcare system in this case; maybe something like: "This is a simplified version of the Canadian health research environment: health is under provincial jurisdiction and each province has health privacy regulations."

2020-03-19 19:42 UTC, ljdursi commented on _posts/2020-03-04-gentle-intro-to-federated-distributed-authz.md
> +- Sites are completely symmetric from a Data Use & Access point of view
Can probably lose that last bullet point; Data Use & Access had a very specific meaning in the GA4GH plenary talk but might not mean anything here.

2020-03-19 21:42 UTC, amanjeev commented
@ljdursi thank you! I have made the changes.

2020-03-20 11:13 UTC, ljdursi approved these changes

2020-03-20 11:14 UTC, merged